# Generated by Django 4.1.1 on 2022-09-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestaurantMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurant_name", models.CharField(max_length=64)),
                ("menu1", models.TextField()),
                ("menu2", models.TextField()),
                ("menu3", models.TextField()),
                ("menu4", models.TextField()),
                ("menu5", models.TextField()),
                ("menu6", models.TextField()),
                ("menu7", models.TextField()),
                ("ratind", models.FloatField()),
            ],
        ),
    ]
